### ISSUE TITLE
small CoNLL-U mistakes

### ISSUE THREAD

**Issue by keggsmurph21** [UniversalDependencies/UD_Erzya-JR#3]
(related to [this pull request](https://github.com/UniversalDependencies/UD_Erzya-JR/pull/2))

i found a few other issues in the file `myv_ChetvergovJevgenij_Velenj-vajgeljtj_1992_UD-dev-2011.conllu` that should be reviewed by an expert

- [ ] on [this line](https://github.com/UniversalDependencies/UD_Erzya-JR/blob/b4e1c82fa4d5f71b7b1e06edcac1930400eed9c9/myv_ChetvergovJevgenij_Velenj-vajgeljtj_1992_UD-dev-2011.conllu#L179), the `head` for token `12` is given as `conj`
 - [ ] on [this line](https://github.com/UniversalDependencies/UD_Erzya-JR/blob/b4e1c82fa4d5f71b7b1e06edcac1930400eed9c9/myv_ChetvergovJevgenij_Velenj-vajgeljtj_1992_UD-dev-2011.conllu#L595), the `deprel` is in the `head` column (and there's no head)
 - [ ] on [this line](https://github.com/UniversalDependencies/UD_Erzya-JR/blob/b4e1c82fa4d5f71b7b1e06edcac1930400eed9c9/myv_ChetvergovJevgenij_Velenj-vajgeljtj_1992_UD-dev-2011.conllu#L1246), the `deprel` is in the `head` column (and there's no head)

**Comment by rueter** [comment]
<pre>
# sent_id = ChetvergovJevgenij_Velenj-vajgeljtj_1992:4665
# text = Ацамокс тень сеетьстэ эрсесь пиже нарось, вельксэкс — тештьсэ сялгонезь менелесь.
1       Ацамокс ацамо   NOUN    N|SP|Tra|Indef  Case=Tra|Definite=Ind|Number=Plur,Sing  4       acl     _       Gloss=bedding
2       тень    мон     PRON    Pron|Pers|Sg1|Dat|Variant=Short Case=Dat|Number=Sing|Person=1|PronType=Prs|Variant=Short        4       obl     _       Gloss=for-me
3       сеетьстэ        сеедьстэ        ADV     Adv|Qnt _       4       advmod  _       Gloss=often
4       эрсесь  эрсемс  VERB    V|IV|Ind|Prt1|ScSg3     Mood=Ind|Number[subj]=Sing|Person[subj]=3|Tense=Prt1|Valency=1  0       root    _       Gloss=occur
5       пиже    пиже    ADJ     A|Attr  _       6       amod    _       Gloss=green
6       нарось  нар     NOUN    N|Sg|Nom|Def    Case=Nom|Definite=Def|Number=Sing       4       nsubj   _       Gloss=grass|SpaceAfter=No
7       ,       ,       PUNCT   CLB     _       8       punct   _       _
8       вельксэкс       велькс  NOUN    N|SP|Tra|Indef  Case=Tra|Definite=Ind|Number=Plur,Sing  12      acl     _       Gloss=cover
9       —       —       PUNCT   PUNCT   _       12      punct   _       _
10      тештьсэ теште   NOUN    N|SP|Ine|Indef  Case=Ine|Definite=Ind|Number=Plur,Sing  11      obl     _       Gloss=star
11      сялгонезь       сялгонемс       VERB    V|TV|Der/Озь|Ger|A|Attr Derivation=Ozj|Valency=2|VerbForm=Conv  12      acl     _       Gloss=pierce
12      менелесь        менель  NOUN    N|Sem/Plc|Sg|Nom|Def    Case=Nom|Definite=Def|Number=Sing       6       conj    _       Gloss=sky|SpaceAfter=No
13      .       .       PUNCT   CLB     _       4       punct   _       _
</pre>

**Comment by jonorthwash** [comment]
@rueter, what do you mean?

**Comment by jonorthwash** [comment]
It looks like the addition of "6" here in line 12 will fix the first of the issues above.  But there seem to be lots of other changes introduced here as well.  Is this some branch or something?
