### ISSUE TITLE
Rename subtype dependency standard of comparison

### ISSUE THREAD

**Issue by rueter** [UniversalDependencies/UD_Erzya-JR#4]
@ftyers @dan-zeman @flammie @jonorthwash  @kailimp @jmnybl   can you help me find people working with Latin, Polish, Tamil, pcm and Vietnamese?

The Finnish and Estonian treebanks do not have this subtype

At present the _obl:comp_ is used for expressing at least two different dependencies:
* In UD_Komi_Zyrian-LATTICE (kpv), UD_Erzya-JR (myv), UD_Moksha-JR (mdf), it is used to indicate
_standard of comparison_, i.e., `bigger _than me_'.
* In (pcm) it is used to express: _nominal arguments which are introduced by a preposition_, which sounds like this might better be written using _case_
* In (vi) nearly the same is present: _oblique nominal with other preposition_, but could this refer to some kind of relational noun?

Thus in Erzya the _standard of comparison_:
~~~ sdparse
...кавалдонть виев ды кавалдонть кежев. \n ...than-the-falcon strong and than-the-falcon mean.
obl:comp(виев-2, кавалдонть-1)
conj(кавалдонть-1, кавалдонть-4)
obl:comp(кежев-5, кавалдонть-4)
obl:comp(strong-2, than-the-falcon-1)
~~~
`... stronger than the falcon and meaner than the falcon.'

The same _standard of comparison_ dependency is expressed in Latin, Polish, Tamil with _obl:cmpr_.
But it is difficult to recognize the parallel usage without reading the specific texts.

To enhance use of UD language projects in parallel, it would be good to change the name of the Erzya, Moksha, Komi-Zyrian deps from _obl:comp_ to _obl:cmpr_.

At the same time, it might be good for the la, pl and ta to specifically refer to the term _standard of comparison_.
Of course, pcm and vi might clarify their usage.

**Comment by dan-zeman** [comment]
> * In (pcm) it is used to express: _nominal arguments which are introduced by a preposition_, which sounds

I don't see `obl:comp` used in Naija in UD 2.10 (https://universaldependencies.org/ext-dep-index.html#obl). Perhaps @sylvainkahane could comment on whether it was/is/will be used there.

It also wasn't used in Vietnamese previously but it seems to be used in the data being prepared for UD 2.11. Perhaps @vietnamesedp could comment on it.

But I agree that it is desirable to unify the subtype that denotes the standard of comparison. In Polish PDB (http://hdl.handle.net/11346/PMLTQ-IIR6), `obl:cmpr` indeed looks like the standard of comparison, both for equative (_jak_) and non-equative (_niż_) comparisons. For Latin, @Stormur might know more, and for Tamil, @sarves. Furthermore, we have `obl:cmp` in Telugu (https://universaldependencies.org/te/dep/obl-cmp.html) for the very same function. In a sense I like `:cmp` the best because it corresponds to the feature `Degree=Cmp`; but sadly, if that is going to be the recommended solution, the highest number of treebanks will have to be fixed.

**Comment by Stormur** [comment]
Since it is only an issue of labelling, it would not be a problem to adjust this for Latin. I also prefer `cmp`. This relation is the same in the cases you mentioned, and it is used independently of the type of comparisono in Latin (so for equatives, too).

**Comment by Stormur** [comment]
> At the same time, it might be good for the la, pl and ta to specifically refer to the term _standard of comparison_.
> Of course, pcm and vi might clarify their usage.

You are right, this shall be done in a next review of Latin documentation!

**Comment by sylvainkahane** [comment]
> I don't see obl:comp used in Naija in UD 2.10 (https://universaldependencies.org/ext-dep-index.html#obl). Perhaps @sylvainkahane could comment on whether it was/is/will be used there.

We changed for `obl:arg`: http://universal.grew.fr/?custom=63161b60afeb3.

**Comment by rueter** [comment]
Great, we will plan to convert obl:comp in Erzya, Moksha and Komi-Zyrian to obl:cmp for *standard of comparison* dependencies. This conversion will also target other uses of the subtype *:comp* in these languages.

@sylvainkahane for the time being, we have not established a distinct dependency for quantifying the extent to which the "boy" is taller than the "old man". Isn't this one of the functions you are using the *obl:arg* for? (see  obl(tall, half-a-head), below)

 ~~~ sdparse
ćorïńkaś at́adońt́ peĺpŕado seŕej. \n the-boy than-the-old-man half-a-head tall.
obl(seŕej, peĺpŕado)
obl:cmp(seŕej, at́adońt́)
nsubj(seŕej, ćorïńkaś)
obl(tall, half-a-head)
obl:cmp(tall, the-old-man)
nsubj(tall, the-boy)

~~~
'The boy is half a head taller than the old man.'

**Comment by sylvainkahane** [comment]
> @sylvainkahane for the time being, we have not established a distinct dependency for quantifying the extent to which the "boy" is taller than the "old man". Isn't this one of the functions you are using the obl:arg for? (see obl(tall, half-a-head), below)

We don't have a specific annotation of comparison. For the complement of _plus_ 'more' in French, we use `obj` for NP and `ccomp` for other cases.
http://universal.grew.fr/?custom=63184f01375d0

**Comment by dan-zeman** [comment]
> Isn't this one of the functions you are using the _obl:arg_ for?

`obl:arg` is used in some treebanks to distinguish oblique arguments from adjuncts, see [here](https://universaldependencies.org/u/dep/obl-arg.html).
